### ISSUE TITLE
Support completion for more asdoc tags

### ISSUE THREAD

**Issue by joshtynjala** [leitwolf/vscode-ASTools#1]
I see that only a few tags are provided in the completion list:

https://github.com/leitwolf/vscode-ASTools/blob/0bbaef4b98294afa4ef2de6da3cf8ed19792eaaf/src/extension.ts#L118-L120

Here's a larger list of asdoc tags that you should include:

https://cwiki.apache.org/confluence/display/FLEX/ASDoc+tags

**Comment by leitwolf** [comment]
support right now.
