### ISSUE TITLE
Code Formatter doesn't work in VsCode(1.47.2)

### ISSUE THREAD

**Issue by yooni126** [leitwolf/vscode-ASTools#7]
recently I update Vscode(1.35.1), but unfortunately, your ActionScript tools seems doesn't work on it
please check it

**Comment by leitwolf** [comment]
work fine on vscode 1.47.3

**Comment by yooni126** [comment]
but unfortunately, when I choose FormatDocumnt in rightClick menu nothing happened also when I run this command with a shortcut  key (ALT+SHIFT+F) vscode prompt me that unable to access jar  file

**Comment by yooni126** [comment]
![image](https://user-images.githubusercontent.com/3766387/89117657-cb67ca00-d4b4-11ea-9c1c-ec5b11878076.png)

**Comment by leitwolf** [comment]
@yooni126 a blank in the path?

**Comment by yooni126** [comment]
yes, it's a ridiculous message! in fact, my windows account is "Mr.Tolid Moblie" but I don't know the rest of the message!
also, I set this command in setting.json
```

  "as3mxml.sdk.framework": "f:\\Tools\\AirSDK\\Air32",
    "as3mxml.java.path": "c:\\Program Files\\Java\\jdk1.8.0_51\\bin\\java.exe",
    "editor.formatOnSave": true,
```

**Comment by leitwolf** [comment]
jar path: C:\Users\Mr.Tolid Moblie\.vscode\extensions\lonewolf.vscode-astools-0.0.6\files\ASPrettyPrinter-1.2.jar
and it is not a valid path, i think.

**Comment by yooni126** [comment]
sorry 
my windows account name had space(Mr Tolid Mobie) and this address caused an error in vsCode that didn't recognize your jar file
so I create a new windows account and now it works like a charm
